Encoding:
  Enabled: false

HashSyntax:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Next:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'Guardfile'
    - 'Berksfile'
