name             'clocker'
maintainer       'James Legg'
maintainer_email 'mail@jameslegg.co.uk'
license          'apachev2'
description      'Installs/Configures clocker'
long_description 'A locking mechanism for chef using zookeeper backend'
version          '0.3.1'
